version: '3.7'

services:

  mysql8:
    image: mysql/mysql-server
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: Sup3rs3cr3t
      MYSQL_DATABASE: testapp
    ports:
      - "3308:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - springapp-network

  springbootapp:
    container_name: springbootapp
    image: springbootapp
    build:
      context: .
      dockerfile: springboot.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./microservice:/opt/app
    networks:
      - springapp-network
    depends_on: 
      - mysql8

networks:
  springapp-network:
    driver: bridge